# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
cache:
  - packages
  - ccache
latex: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libgdal-dev
