# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
dist: trusty
# cache: packages

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes --allow-unauthenticated libgdal-dev

r-packages:
  - rgdal
  - devtools
